enableAllRules = true

[rule.line-length-limit]
  arguments = [200]

[rule.import-alias-naming]
  arguments = ["^[a-z][a-z0-9_]*(V[0-9]+)?$"]
  Disabled = true

[rule.cyclomatic]
  arguments = [42]
[rule.cognitive-complexity]
  arguments = [60]

[rule.unhandled-error]
  arguments = ["fmt.Print", "fmt.Printf", "fmt.Println", "strings.Builder.WriteString", "bytes.Buffer.WriteString"]

[rule.unexported-return]
  Disabled = true

[rule.exported]
  Disabled = true

[rule.package-comments]
  Disabled = true

[rule.max-public-structs]
  Disabled = true

[rule.add-constant]
  Disabled = true

[rule.redundant-import-alias]
  disabled = true

[rule.package-directory-mismatch]
  disabled = true

[rule.enforce-switch-style]
  disabled = true

[rule.struct-tag] # tag inline unrecognized
  disabled = true

[rule.function-length]
  arguments = [100, 150]

[rule.argument-limit]
  arguments = [10]

# during switch to revive from golangci-lint temporarily disable this rule
[rule.var-naming]
  arguments = [[], [], [{skipPackageNameChecks = true}]]
  Disabled = true

[rule.use-any]
  Disabled = true

[rule.import-shadowing]
  Disabled = true

[rule.unused-parameter]
  Disabled = true

[rule.unused-receiver]
  Disabled = true

[rule.flag-parameter]
  Disabled = true

[rule.confusing-naming]
  Disabled = true

[rule.filename-format]
  Disabled = true
